=== Nasibulin/NIIT/Groups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Groups" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Groups">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="GROUP_ID" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="GROUP" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HEAD_ID" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Nasibulin/NIIT/Groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Groups.xsd" generated="2018-10-15T13:28:28">
<Groups>
<GROUP_ID>1</GROUP_ID>
<GROUP>Фундаментальная информатика и информационные технологии</GROUP>
</Groups>
<Groups>
<GROUP_ID>2</GROUP_ID>
<GROUP>Программная инженерия</GROUP>
</Groups>
<Groups>
<GROUP_ID>3</GROUP_ID>
<GROUP>Прикладная математика и информатика</GROUP>
</Groups>
</dataroot>
